---
- name: Debug HashiCorp Vault lookup
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Get entire secret from Vault
      ansible.builtin.set_fact:
        full_secret: "{{ lookup('community.hashi_vault.vault_kv2_get', 'secret/data/1-static-secret/MyFirstSecret') }}"
      # You will see a warning here, but that's expected.

    - name: Print the keys of the secret to find the right field
      debug:
        msg: "The secret contains the following keys: {{ full_secret.keys() }}"
