---
- name: Akeyless AWX Example
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Show Akeyless-injected credentials
      debug:
        msg: "Secret username is {{ APP_USERNAME }} and password is {{ APP_PASSWORD }}"
