---
- name: Akeyless AWX Example
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Show Akeyless-injected credentials
      debug:
      msg: "Secret username is {{ username }} and password is {{ password }}"
