---
- name: Akeyless AWX Example
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Dump all variables (for debugging)
      debug:
        var: hostvars[inventory_hostname]
